# Site settings
title: SF Stress Less - Home Organization in San San Francisco

email: kristin.l.fugitt@gmail.com

description: >
  Get your work, home and life in order with a home organization coach!
  Kristin can help you reduce your stress and improve your happiness.

baseurl: ""

url: "https://sfstressless.com"

environment: production

# Build settings
markdown: kramdown
